apiVersion: v1
kind: Pod
metadata:
  name: data-pod
spec:
  nodeSelector:
    #topology.kubernetes.io/region: us-west
    nautilus.io/linstor: "true"
  
  containers:
    - name: brats-processing
      image: gitlab-registry.nrp-nautilus.io/prp/jupyter-stack/prp
      
      command: ["/bin/bash", "-c"]
      args:
        - |
          sudo apt update && sudo apt install zip
          # pip install --upgrade synapseclient 

          # run the below in kubectl exec -- bash s
          # synapse get syn51669979  
          # will prompt for token obtained at https://accounts.synapse.org/authenticated/personalaccesstokens

          tail -f /dev/null
      
      volumeMounts:
        - name: workspace
          mountPath: /app
        - name: data4
          mountPath: /data4
        - name: data5
          mountPath: /data5
        - name: data6
          mountPath: /data6
        - name: shm
          mountPath: /dev/shm
      resources:
        requests:
          memory: 24Gi      
          cpu: "12"     
        limits:
          memory: 32Gi
          cpu: "16"
      
  
  volumes:
    - name: workspace
      emptyDir:
        sizeLimit: 50Gi
    - name: data4
      persistentVolumeClaim:
        claimName: brats2025-4
    - name: data5
      persistentVolumeClaim:
        claimName: brats2025-5
    - name: data6
      persistentVolumeClaim:
        claimName: brats2025-6
    - name: shm
      emptyDir:
        medium: Memory
        sizeLimit: 16Gi
  
  restartPolicy: Never