apiVersion: v1
kind: Pod
metadata:
  name: openmx-hamgnn
spec:
  nodeSelector:
    #topology.kubernetes.io/region: us-west
    nautilus.io/linstor: "true"
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: nvidia.com/gpu.product
            operator: In
            values:
            - NVIDIA-A10
            - NVIDIA-GeForce-RTX-3090
            - NVIDIA-GeForce-RTX-4090
            - NVIDIA-TITAN-RTX
            - NVIDIA-RTX-A5000
            - Quadro-RTX-6000
            - Tesla-V100-SXM2-32GB
            - NVIDIA-A40
            - NVIDIA-L40
            - NVIDIA-RTX-A6000
            - Quadro-RTX-8000

  tolerations:
    - key: nvidia.com/gpu
      operator: Exists
    - key: nvidia.com/gpu
      operator: Exists
      effect: PreferNoSchedule
  containers:
    - name: brats-processing
      image: gitlab-registry.nrp-nautilus.io/prp/jupyter-stack/prp

      command: ["/bin/bash", "-c"]
      args:
        - |
          cp /data/openmx3.9.tar.gz .

          sudo apt update

          # Install compilers
          sudo apt install gcc gfortran

          # Install MPI
          sudo apt install libopenmpi-dev openmpi-bin

          # Install FFTW library
          sudo apt install libfftw3-dev

          # Install additional development tools that might be needed
          sudo apt install make build-essential

          tar -xzvf openmx3.9.tar.gz 

          tail -f /dev/null
     
      volumeMounts:
        - name: workspace
          mountPath: /app
        - name: shm
          mountPath: /dev/shm
        - name: data
          mountPath: /data
    
      resources:
        requests:
          memory: 24Gi
          cpu: "12"
          nvidia.com/gpu: "1"
        limits:
          memory: 32Gi
          cpu: "16"
          nvidia.com/gpu: "1"
 
  volumes:
    - name: workspace
      emptyDir:
        sizeLimit: 50Gi
    - name: data
      persistentVolumeClaim:
        claimName: openmx-1 
    - name: shm
      emptyDir:
        medium: Memory
        sizeLimit: 16Gi
 
  restartPolicy: Never