apiVersion: v1
kind: Pod
metadata:
  name: openmx
spec:
  nodeSelector:
    #topology.kubernetes.io/region: us-west
    nautilus.io/linstor: "true"
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: nvidia.com/gpu.product
            operator: In
            values:
            - NVIDIA-A10
            - NVIDIA-GeForce-RTX-3090
            - NVIDIA-GeForce-RTX-4090
            - NVIDIA-TITAN-RTX
            - NVIDIA-RTX-A5000
            - Quadro-RTX-6000
            - Tesla-V100-SXM2-32GB
            - NVIDIA-A40
            - NVIDIA-L40
            - NVIDIA-RTX-A6000
            - Quadro-RTX-8000

  tolerations:
    - key: nvidia.com/gpu
      operator: Exists
    - key: nvidia.com/gpu
      operator: Exists
      effect: PreferNoSchedule
  containers:
    - name: brats-processing
      image: ubuntu

      command: ["/bin/bash", "-c"]
      args:
      - |
        apt update
        apt install -y gcc gfortran
        apt install -y liblapack-dev libblas-dev
        apt install -y libopenmpi-dev openmpi-bin
        apt install -y libscalapack-mpi-dev
        apt install -y libfftw3-dev
        apt install -y make build-essential
        
        tar -xzvf /data/openmx3.8.tar.gz
        cd openmx3.8/source
        
        cp /data/makefile .
        
        make clean
        make
        
        cd ../work
        cp ../source/openmx .

        ls -la met.*

        useradd -m -s /bin/bash openmx
        chown -R openmx:openmx /openmx3.8
        
        su - openmx -c "cd /openmx3.8/work && mpirun -np 1 ./openmx Methane.dat > met.std 2>&1"
        
        ls -la met.*
        
        tail -f /dev/null
     
      volumeMounts:
        - name: workspace
          mountPath: /app
        - name: shm
          mountPath: /dev/shm
        - name: data
          mountPath: /data
    
      resources:
        requests:
          memory: 24Gi
          cpu: "12"
          nvidia.com/gpu: "1"
        limits:
          memory: 32Gi
          cpu: "16"
          nvidia.com/gpu: "1"
 
  volumes:
    - name: workspace
      emptyDir:
        sizeLimit: 50Gi
    - name: data
      persistentVolumeClaim:
        claimName: openmx-1 
    - name: shm
      emptyDir:
        medium: Memory
        sizeLimit: 16Gi
 
  restartPolicy: Never