apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: KBO-OO-Prediction-1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: linstor-sdsu 